export const GET_BOOKMARKS_REQUEST = 'GET_BOOKMARKS_REQUEST';
export const GET_BOOKMARKS_SUCCESS = 'GET_BOOKMARKS_SUCCESS';
export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const BOOKMARKS_META_CHANGE = 'BOOKMARKS_META_CHANGE';
export const USERS_META_CHANGE = 'USERS_META_CHANGE';
