files:
  include: src/**/*.scss
options:
  formatter: stylish
  merge-default-rules: false
rules:
  border-zero: 0
  class-name-format:
    - 2
    - convention: hyphenatedbem
  id-name-format:
    - 2
    - convention: hyphenatedbem
  indentation:
    - 2
    - size: 2
  leading-zero: 0
  placeholder-name-format:
    - 2
    - convention: hyphenatedbem
  property-sort-order:
    - 2
    - order: smacss
