export const GET_MY_BOOKMARKS_REQUEST = 'GET_MY_BOOKMARKS_REQUEST';
export const GET_MY_BOOKMARKS_SUCCESS = 'GET_MY_BOOKMARKS_SUCCESS';
export const CREATE_BOOKMARK_REQUEST = 'CREATE_BOOKMARK_REQUEST';
export const UPDATE_BOOKMARK_REQUEST = 'UPDATE_BOOKMARK_REQUEST';
export const DELETE_BOOKMARK_REQUEST = 'DELETE_BOOKMARK_REQUEST';
export const DELETE_BOOKMARK_SUCCESS = 'DELETE_BOOKMARK_SUCCESS';
export const SELECTED_BOOKMARK_CHANGE = 'SELECTED_BOOKMARK_CHANGE';
